[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "6djtCuysGb4B9v7EBwqZPdTWLBdQsu3BJjqLYo6xsad"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
